<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate_RandomForestRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset

In [2]:
import io
from google.colab import files

In [3]:
uploaded = files.upload()

Saving 0041 83493 Rev07.csv to 0041 83493 Rev07 (3).csv


In [4]:
dataset = pd.read_csv(io.BytesIO(uploaded['0041 83493 Rev07.csv']))

In [5]:
dataset

Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                               5.999
1                    CP471589 (301514-2921-0007)  ...                               5.999
2                    CP471589 (301514-2921-0008)  ...                               5.999
3                    CP471589 (301514-2921-0009)  ...                               6.000
4                    CP471589 (301514-2921-0010)  ...                               5.999
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                               5.999
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                               6.000
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                               5.999
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                               6.000
71  CP472178 (0041-83493_07_SN 301514-3221-0070)  ...                               6.000

[72 rows x 133 columns]

In [6]:
X = dataset.iloc[:,19: ].values
Y = dataset.iloc[:,1:2].values

In [7]:
print(X)

[[4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0490e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1700e-01 5.0440e+00 5.9990e+00]
 ...
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 6.0000e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0400e+00 6.0000e+00]]


In [8]:
print(Y)

[[14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.018]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.018]
 [14.016]
 [14.017]
 [14.018]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.018]
 [14.017]
 [14.016]
 [14.018]
 [14.017]]


In [9]:
dataset.shape

(72, 133)

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 133 entries, Job # to 6.000_R +/-0.005 (SH2_C7_Distance)
dtypes: float64(132), object(1)
memory usage: 74.9+ KB


# Taking care of missing data

Impute Missing Values. 

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:,:] = imputer.transform(X[:,:])

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Y[:,:])
Y[:,:] = imputer.transform(Y[:,:])

In [13]:
print(X)

[[4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0490e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1700e-01 5.0440e+00 5.9990e+00]
 ...
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 6.0000e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0400e+00 6.0000e+00]]


In [14]:
print(Y)

[[14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.018]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.018]
 [14.016]
 [14.017]
 [14.018]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.018]
 [14.017]
 [14.016]
 [14.018]
 [14.017]]


Check the percentage of missing values in each variable.

In [15]:
dataset.isnull().sum()/len(dataset)*100

Job #                                    0.0
14.020 +0.0/-0.005 (SH1_C2_Diameter)     0.0
0.220 +0.005/-0.0 (SH1_B5_Diameter)      0.0
0.160 +/- 0.002 (SH1_B5_Diameter)        0.0
0.005 +0.0/-0.005 (SH1_B5_Position)      0.0
                                        ... 
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)    0.0
0.118 +/-0.005 (SH4_C7_Distance_1_Z)     0.0
0.118 +/-0.005 (SH4_C7_Distance_2_Y)     0.0
5 Deg +/- 1 (SH2_B8_Angle)               0.0
6.000_R +/-0.005 (SH2_C7_Distance)       0.0
Length: 133, dtype: float64

# Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [17]:
print(X_train)

[[4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1700e-01 5.0370e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 6.0000e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1700e-01 5.0400e+00 6.0000e+00]
 ...
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0480e+00 5.9990e+00]
 [4.6900e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0420e+00 5.9990e+00]
 [4.6900e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0470e+00 5.9990e+00]]


In [18]:
print(X_test)

[[4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0470e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0420e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0530e+00 5.9990e+00]
 ...
 [4.7000e-01 1.1000e+01 1.2000e+02 ... 1.1800e-01 5.0430e+00 6.0000e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0480e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0460e+00 5.9990e+00]]


In [19]:
print(Y_train)

[[14.019]
 [14.018]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.018]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.018]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.016]
 [14.018]
 [14.018]
 [14.019]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.019]
 [14.016]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.016]]


In [20]:
print(Y_test)

[[14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]]


# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [22]:
print(X_train)

[[ 0.20378479 -0.46923713  0.         ... -1.13586028 -2.00133168
  -0.85280287]
 [ 0.20378479 -0.46923713  0.         ...  0.76837607 -0.99403891
   1.17260394]
 [ 0.20378479 -0.46923713  0.         ... -1.13586028 -1.24586211
   1.17260394]
 ...
 [ 0.20378479 -0.46923713  0.         ...  0.76837607  0.76872343
  -0.85280287]
 [-2.11936178 -0.46923713  0.         ...  0.76837607 -0.74221572
  -0.85280287]
 [-2.11936178 -0.46923713  0.         ...  0.76837607  0.51690024
  -0.85280287]]


In [23]:
print(X_test)

[[ 0.20378479 -0.46923713  0.         ...  0.76837607  0.51690024
  -0.85280287]
 [ 0.20378479 -0.46923713  0.         ...  0.76837607 -0.74221572
  -0.85280287]
 [ 0.20378479 -0.46923713  0.         ...  0.76837607  2.02783938
  -0.85280287]
 ...
 [ 0.20378479  1.75963925  0.         ...  0.76837607 -0.49039253
   1.17260394]
 [ 0.20378479 -0.46923713  0.         ...  0.76837607  0.76872343
  -0.85280287]
 [ 0.20378479 -0.46923713  0.         ...  0.76837607  0.26507704
  -0.85280287]]


Low Variance Filter: Calculate the variance of all the numerical variables

In [24]:
dataset.var()

14.020 +0.0/-0.005 (SH1_C2_Diameter)     5.772692e-07
0.220 +0.005/-0.0 (SH1_B5_Diameter)      1.953056e-32
0.160 +/- 0.002 (SH1_B5_Diameter)        7.812223e-32
0.005 +0.0/-0.005 (SH1_B5_Position)      3.644366e-07
0.190 +0.002/-0.0 (SH1_B1_Width)         1.249956e-32
                                             ...     
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)    1.672535e-07
0.118 +/-0.005 (SH4_C7_Distance_1_Z)     6.148279e-07
0.118 +/-0.005 (SH4_C7_Distance_2_Y)     2.580203e-07
5 Deg +/- 1 (SH2_B8_Angle)               1.732394e-05
6.000_R +/-0.005 (SH2_C7_Distance)       2.439358e-07
Length: 132, dtype: float64

High Correlation Filter

In [25]:
df=dataset.drop('Job #', 1)
df.corr()

14.020 +0.0/-0.005 (SH1_C2_Diameter)  ...  6.000_R +/-0.005 (SH2_C7_Distance)
14.020 +0.0/-0.005 (SH1_C2_Diameter)                           1.000000e+00  ...                       -5.265063e-02
0.220 +0.005/-0.0 (SH1_B5_Diameter)                           -1.530352e-11  ...                       -1.008582e-11
0.160 +/- 0.002 (SH1_B5_Diameter)                             -1.530352e-11  ...                       -1.008582e-11
0.005 +0.0/-0.005 (SH1_B5_Position)                            2.430994e-02  ...                        4.526989e-02
0.190 +0.002/-0.0 (SH1_B1_Width)                               1.530352e-11  ...                        1.008582e-11
...                                                                     ...  ...                                 ...
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)                         -3.588452e-02  ...                       -2.062829e-01
0.118 +/-0.005 (SH4_C7_Distance_1_Z)                          -3.119369e-02  ...                       -1.550718e-01
0.118 +/-0.005 (SH4_C7_Distance_2_Y)                           8.566032e-02  ...                       -2.206637e-01
5 Deg +/- 1 (SH2_B8_Angle)                                    -1.885435e-01  ...                       -6.623037e-02
6.000_R +/-0.005 (SH2_C7_Distance)                            -5.265063e-02  ...                        1.000000e+00

[132 rows x 132 columns]

# Training the Random Forest Regression model on the whole dataset

In [26]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, Y)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(n_estimators=10, random_state=0)

Predicting the Test set results

In [27]:
Y_pred = regressor.predict(X)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y.reshape(len(Y),1)),1))

[[14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14.02]
 [14.02 14

Getting the final linear regression equation with the values of the coefficients

In [28]:
print(regressor.coef_)
print(regressor.intercept_)

AttributeError: ignored

# Evaluating the Model Performance

In [30]:
from sklearn.metrics import r2_score
r2_score(Y, Y_pred)

0.7806574042704116