<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
import io
from google.colab import files

In [8]:
uploaded = files.upload()

Saving 0041 83493 Rev07.csv to 0041 83493 Rev07.csv


In [9]:
dataset = pd.read_csv(io.BytesIO(uploaded['0041 83493 Rev07.csv']))

In [10]:
uploaded.keys()

dict_keys(['0041 83493 Rev07.csv'])

In [11]:
dataset

Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                               5.999
1                    CP471589 (301514-2921-0007)  ...                               5.999
2                    CP471589 (301514-2921-0008)  ...                               5.999
3                    CP471589 (301514-2921-0009)  ...                               6.000
4                    CP471589 (301514-2921-0010)  ...                               5.999
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                               5.999
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                               6.000
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                               5.999
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                               6.000
71  CP472178 (0041-83493_07_SN 301514-3221-0070)  ...                               6.000

[72 rows x 133 columns]

In [12]:
df = dataset.values

In [13]:
df

array([['CP471589 (301514-2921-0006)', 14.017000000000001, 0.222, ...,
        0.11800000000000001, 5.041, 5.999],
       ['CP471589 (301514-2921-0007)', 14.017000000000001, 0.222, ...,
        0.11800000000000001, 5.0489999999999995, 5.999],
       ['CP471589 (301514-2921-0008)', 14.017000000000001, 0.222, ...,
        0.11699999999999999, 5.044, 5.999],
       ...,
       ['CP472178 (0041-83493_07_SN 301514-3221-0068)',
        14.015999999999998, 0.222, ..., 0.11800000000000001, 5.041,
        5.999],
       ['CP472178 (0041-83493_07_SN 301514-3221-0069)',
        14.017999999999999, 0.222, ..., 0.11800000000000001, 5.041, 6.0],
       ['CP472178 (0041-83493_07_SN 301514-3221-0070)',
        14.017000000000001, 0.222, ..., 0.11800000000000001, 5.04, 6.0]],
      dtype=object)

In [14]:
dataset.head

<bound method NDFrame.head of                                            Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                               5.999
1                    CP471589 (301514-2921-0007)  ...                               5.999
2                    CP471589 (301514-2921-0008)  ...                               5.999
3                    CP471589 (301514-2921-0009)  ...                               6.000
4                    CP471589 (301514-2921-0010)  ...                               5.999
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                               5.999
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                               6.000
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                               5.999
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                 

In [15]:
dataset.shape

(72, 133)

In [16]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 133 entries, Job # to 6.000_R +/-0.005 (SH2_C7_Distance)
dtypes: float64(132), object(1)
memory usage: 74.9+ KB


In [17]:
dataset.values

array([['CP471589 (301514-2921-0006)', 14.017000000000001, 0.222, ...,
        0.11800000000000001, 5.041, 5.999],
       ['CP471589 (301514-2921-0007)', 14.017000000000001, 0.222, ...,
        0.11800000000000001, 5.0489999999999995, 5.999],
       ['CP471589 (301514-2921-0008)', 14.017000000000001, 0.222, ...,
        0.11699999999999999, 5.044, 5.999],
       ...,
       ['CP472178 (0041-83493_07_SN 301514-3221-0068)',
        14.015999999999998, 0.222, ..., 0.11800000000000001, 5.041,
        5.999],
       ['CP472178 (0041-83493_07_SN 301514-3221-0069)',
        14.017999999999999, 0.222, ..., 0.11800000000000001, 5.041, 6.0],
       ['CP472178 (0041-83493_07_SN 301514-3221-0070)',
        14.017000000000001, 0.222, ..., 0.11800000000000001, 5.04, 6.0]],
      dtype=object)

In [18]:
print(dataset)

                                           Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                               5.999
1                    CP471589 (301514-2921-0007)  ...                               5.999
2                    CP471589 (301514-2921-0008)  ...                               5.999
3                    CP471589 (301514-2921-0009)  ...                               6.000
4                    CP471589 (301514-2921-0010)  ...                               5.999
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                               5.999
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                               6.000
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                               5.999
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                               6.000
71  CP4721

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df[:, 1:132])
df[:, 1:132] = imputer.transform(df[:, 1:132])

In [20]:
print(df)

[['CP471589 (301514-2921-0006)' 14.017000000000001 0.222 ...
  0.11800000000000001 5.041 5.999]
 ['CP471589 (301514-2921-0007)' 14.017000000000001 0.222 ...
  0.11800000000000001 5.0489999999999995 5.999]
 ['CP471589 (301514-2921-0008)' 14.017000000000001 0.222 ...
  0.11699999999999999 5.044 5.999]
 ...
 ['CP472178 (0041-83493_07_SN 301514-3221-0068)' 14.015999999999998 0.222
  ... 0.11800000000000001 5.041 5.999]
 ['CP472178 (0041-83493_07_SN 301514-3221-0069)' 14.017999999999999 0.222
  ... 0.11800000000000001 5.041 6.0]
 ['CP472178 (0041-83493_07_SN 301514-3221-0070)' 14.017000000000001 0.222
  ... 0.11800000000000001 5.04 6.0]]


In [21]:
dataset

Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                               5.999
1                    CP471589 (301514-2921-0007)  ...                               5.999
2                    CP471589 (301514-2921-0008)  ...                               5.999
3                    CP471589 (301514-2921-0009)  ...                               6.000
4                    CP471589 (301514-2921-0010)  ...                               5.999
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                               5.999
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                               6.000
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                               5.999
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                               6.000
71  CP472178 (0041-83493_07_SN 301514-3221-0070)  ...                               6.000

[72 rows x 133 columns]

In [22]:
X_train = dataset.iloc[:, 1: ].values

In [23]:
print(X_train)

[[14.017  0.222  0.161 ...  0.118  5.041  5.999]
 [14.017  0.222  0.161 ...  0.118  5.049  5.999]
 [14.017  0.222  0.161 ...  0.117  5.044  5.999]
 ...
 [14.016  0.222  0.161 ...  0.118  5.041  5.999]
 [14.018  0.222  0.161 ...  0.118  5.041  6.   ]
 [14.017  0.222  0.161 ...  0.118  5.04   6.   ]]


**Feature** **Scaling**

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:] = sc.fit_transform(X_train[:,:])

In [25]:
print(X_train)

[[-0.01840837  0.          0.         ...  0.68836315 -1.04842119
  -0.82122993]
 [-0.01840837  0.          0.         ...  0.68836315  0.88712562
  -0.82122993]
 [-0.01840837  0.          0.         ... -1.29412271 -0.32259114
  -0.82122993]
 ...
 [-1.3438112   0.          0.         ...  0.68836315 -1.04842119
  -0.82122993]
 [ 1.30699445  0.          0.         ...  0.68836315 -1.04842119
   1.21768576]
 [-0.01840837  0.          0.         ...  0.68836315 -1.29036454
   1.21768576]]


In [26]:
dataset.var()

14.020 +0.0/-0.005 (SH1_C2_Diameter)     5.772692e-07
0.220 +0.005/-0.0 (SH1_B5_Diameter)      1.953056e-32
0.160 +/- 0.002 (SH1_B5_Diameter)        7.812223e-32
0.005 +0.0/-0.005 (SH1_B5_Position)      3.644366e-07
0.190 +0.002/-0.0 (SH1_B1_Width)         1.249956e-32
                                             ...     
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)    1.672535e-07
0.118 +/-0.005 (SH4_C7_Distance_1_Z)     6.148279e-07
0.118 +/-0.005 (SH4_C7_Distance_2_Y)     2.580203e-07
5 Deg +/- 1 (SH2_B8_Angle)               1.732394e-05
6.000_R +/-0.005 (SH2_C7_Distance)       2.439358e-07
Length: 132, dtype: float64

In [30]:
dataset.isnull().sum()/len(dataset)*100

Job #                                    0.0
14.020 +0.0/-0.005 (SH1_C2_Diameter)     0.0
0.220 +0.005/-0.0 (SH1_B5_Diameter)      0.0
0.160 +/- 0.002 (SH1_B5_Diameter)        0.0
0.005 +0.0/-0.005 (SH1_B5_Position)      0.0
                                        ... 
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)    0.0
0.118 +/-0.005 (SH4_C7_Distance_1_Z)     0.0
0.118 +/-0.005 (SH4_C7_Distance_2_Y)     0.0
5 Deg +/- 1 (SH2_B8_Angle)               0.0
6.000_R +/-0.005 (SH2_C7_Distance)       0.0
Length: 133, dtype: float64