<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate_MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

# Importing the libraries

In [673]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Importing the dataset

In [674]:
import io
from google.colab import files

In [675]:
uploaded = files.upload()

Saving 0041-83493_Rev07.csv to 0041-83493_Rev07 (19).csv


In [676]:
dataset = pd.read_csv(io.BytesIO(uploaded['0041-83493_Rev07.csv']))

In [677]:
dataset

SN (JOB #)  SH1_C2_Diameter -14.020  \
0              IPI-001_SN0001 (CP467059)                14.017400   
1               0 DEG SN 0002 (CP471589)                14.016011   
2              90 DEG SN 0003 (CP471589)                14.015942   
3             180 DEG SN 0004 (CP471589)                14.018477   
4               SN0005 270DEG (CP471589)                14.016071   
..                                   ...                      ...   
87  SN 301514-5021-0256 (CP474149_REV08)                14.015503   
88  SN 301514-5021-0257 (CP474149_REV08)                14.015220   
89  SN 301514-5021-0258 (CP474149_REV08)                14.015178   
90  SN 301514-5021-0259 (CP474149_REV08)                14.017048   
91  SN 301514-5021-0260 (CP474149_REV08)                14.017311   

    SH1_B5_Diameter -0.220  SH1_B5_Diameter -0.160  SH1_B5_Position -0.005  \
0                 0.222300                0.161250                0.000700   
1                 0.221733                0.161174                0.000481   
2                 0.221904                0.161202                0.000903   
3                 0.221841                0.161174                0.000434   
4                 0.221928                0.161158                0.000481   
..                     ...                     ...                     ...   
87                0.221326                0.160738                0.000396   
88                0.221238                0.160695                0.001317   
89                0.221296                0.160680                0.000526   
90                0.221358                0.160751                0.000183   
91                0.221343                0.160738                0.000401   

    SH1_B1_Width -0.190  SH1_B1_Distance -0.200  SH1_B1_Position- 0.002  \
0              0.192200                0.198800                0.000000   
1              0.191812                0.200574                0.000000   
2              0.191788                0.200091                0.000000   
3              0.191770                0.200465                0.000000   
4              0.191820                0.200294                0.000000   
..                  ...                     ...                     ...   
87             0.191336                0.200956                0.000008   
88             0.191349                0.200278                0.000000   
89             0.191342                0.200183                0.000000   
90             0.191340                0.200260                0.000000   
91             0.191361                0.200214                0.000000   

    SH1_D5_Position -0.005  SH2_D7_Width -0.190  ...  SH4_B7_Width -0.065  \
0                 0.001100             0.192200  ...             0.068400   
1                 0.001154             0.191750  ...             0.067757   
2                 0.001015             0.191730  ...             0.067760   
3                 0.001113             0.191971  ...             0.067707   
4                 0.000876             0.191710  ...             0.067761   
..                     ...                  ...  ...                  ...   
87                0.001500             0.191257  ...             0.067776   
88                0.001034             0.191284  ...             0.067780   
89                0.000821             0.191169  ...             0.067780   
90                0.000817             0.191211  ...             0.067777   
91                0.001026             0.191211  ...             0.067797   

    SH3_B8_Position -0.005  SH3_B7_Distance -0.100  SH4_C7_Radius -0.0325  \
0                 0.001200                0.098950               0.033800   
1                 0.002455                0.102773               0.033507   
2                 0.001692                0.102942               0.033518   
3                 0.002165                0.102567               0.033509   
4                 0.001043                0.102188   

In [678]:
X = dataset.iloc[:,19: ].values
Y = dataset.iloc[:,18:19].values

In [679]:
print(X)

[[4.7182500e-01 1.1000900e+01 1.2000000e+02 ... 1.1725000e-01
  5.0403000e+00 6.0002000e+00]
 [4.6883000e-01 1.0999463e+01 1.2000000e+02 ... 1.1741200e-01
  5.0566710e+00 6.0000130e+00]
 [4.6884700e-01 1.0999496e+01 1.2000000e+02 ... 1.1746900e-01
  5.0501160e+00 5.9999630e+00]
 ...
 [4.7053200e-01 1.1000375e+01 1.2000000e+02 ... 1.1864000e-01
  5.0447630e+00 6.0001260e+00]
 [4.7054400e-01 1.1000954e+01 1.2000000e+02 ... 1.1850800e-01
  5.0460670e+00 6.0003820e+00]
 [4.7053600e-01 1.1000676e+01 1.2000000e+02 ... 1.1868600e-01
  5.0462200e+00 6.0001930e+00]]


In [680]:
print(Y)

[[   nan]
 [   nan]
 [   nan]
 [   nan]
 [0.099 ]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1005]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1005]
 [0.1015]
 [0.1015]
 [0.1014]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1005]
 [0.1005]
 [0.101 ]
 [0.1005]
 [0.1005]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.1005]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1005]
 [0.1005]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1005]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.1005]
 [0.101 ]
 [0.1015]
 [0.1005]
 [0.1015]
 [0.1015]
 [0.1005]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.101 ]
 [0.1   ]
 [0.1   ]
 [0.1   ]
 [0.1005]
 [0.1005]
 [0.101 ]
 [0.1   ]
 [0.1008]
 [0.1005]
 [0.1   ]
 [0.1   ]
 [0.1   ]
 [0.1005]
 [0.101 ]
 [0.1   ]
 [0.102 ]
 [0.102 ]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.102 ]]


In [681]:
dataset.shape

(92, 129)

In [682]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Columns: 129 entries, SN (JOB #) to SH2_C7_Distance -6.000_R
dtypes: float64(127), int64(1), object(1)
memory usage: 92.8+ KB


# Taking care of missing data

Impute Missing Values. 

In [683]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:,:] = imputer.transform(X[:,:])

In [684]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Y[:,:])
Y[:,:] = imputer.transform(Y[:,:])

In [685]:
print(X)

[[4.7182500e-01 1.1000900e+01 1.2000000e+02 ... 1.1725000e-01
  5.0403000e+00 6.0002000e+00]
 [4.6883000e-01 1.0999463e+01 1.2000000e+02 ... 1.1741200e-01
  5.0566710e+00 6.0000130e+00]
 [4.6884700e-01 1.0999496e+01 1.2000000e+02 ... 1.1746900e-01
  5.0501160e+00 5.9999630e+00]
 ...
 [4.7053200e-01 1.1000375e+01 1.2000000e+02 ... 1.1864000e-01
  5.0447630e+00 6.0001260e+00]
 [4.7054400e-01 1.1000954e+01 1.2000000e+02 ... 1.1850800e-01
  5.0460670e+00 6.0003820e+00]
 [4.7053600e-01 1.1000676e+01 1.2000000e+02 ... 1.1868600e-01
  5.0462200e+00 6.0001930e+00]]


In [686]:
print(Y)

[[0.10097386]
 [0.10097386]
 [0.10097386]
 [0.10097386]
 [0.099     ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.1005    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1005    ]
 [0.1015    ]
 [0.1015    ]
 [0.1014    ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1005    ]
 [0.1005    ]
 [0.101     ]
 [0.1005    ]
 [0.1005    ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1005    ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.1005    ]
 [0.1005    ]
 [0.101     ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.1005    ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1005    ]
 [0.101     ]
 [0.1015    ]
 [0.1005    ]
 [0.1015    ]
 [0.1015    ]
 [0.1005    ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.101     ]
 [0.1       ]
 [0.1 

Check the percentage of missing values in each variable.

In [687]:
dataset.isnull().sum()/len(dataset)*100

SN (JOB #)                  0.0
SH1_C2_Diameter -14.020     0.0
SH1_B5_Diameter -0.220      0.0
SH1_B5_Diameter -0.160      0.0
SH1_B5_Position -0.005      0.0
                           ... 
SH4_D8_Distance -0.235      0.0
SH4_B7_Distance -0.148      0.0
SH4_C7_Distance -0.118      0.0
SH2_B8_Angle -5 Deg         0.0
SH2_C7_Distance -6.000_R    0.0
Length: 129, dtype: float64

# Splitting the dataset into the Training set and Test set

In [688]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [689]:
print(X_train)

[[4.7016300e-01 1.0998823e+01 1.2000000e+02 ... 1.1885300e-01
  5.0470340e+00 5.9989620e+00]
 [4.7019100e-01 1.0999411e+01 1.2000000e+02 ... 1.1876800e-01
  5.0430360e+00 5.9999250e+00]
 [4.7021300e-01 1.0999574e+01 1.2000000e+02 ... 1.1877800e-01
  5.0447630e+00 5.9995920e+00]
 ...
 [4.7018800e-01 1.0998534e+01 1.2000000e+02 ... 1.1855600e-01
  5.0480420e+00 5.9986600e+00]
 [4.7020400e-01 1.0998944e+01 1.2000000e+02 ... 1.1873700e-01
  5.0483340e+00 5.9991830e+00]
 [4.7019600e-01 1.0999315e+01 1.2000000e+02 ... 1.1854600e-01
  5.0421470e+00 5.9996080e+00]]


In [690]:
print(X_test)

[[4.6884700e-01 1.0999496e+01 1.2000000e+02 ... 1.1746900e-01
  5.0501160e+00 5.9999630e+00]
 [4.7024800e-01 1.1000206e+01 1.2000000e+02 ... 1.1874900e-01
  5.0457510e+00 6.0001000e+00]
 [4.7018000e-01 1.0999163e+01 1.2000000e+02 ... 1.1790500e-01
  5.0523600e+00 5.9995220e+00]
 ...
 [4.7004900e-01 1.0999397e+01 1.2000000e+02 ... 1.1822800e-01
  5.0465640e+00 5.9995800e+00]
 [4.7048700e-01 1.0998217e+01 1.2000000e+02 ... 1.1839800e-01
  5.0464700e+00 5.9987200e+00]
 [4.6870100e-01 1.0999164e+01 1.2000000e+02 ... 1.1850900e-01
  5.0440660e+00 5.9995690e+00]]


In [691]:
print(Y_train)

[[0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.1008    ]
 [0.1005    ]
 [0.1005    ]
 [0.101     ]
 [0.1       ]
 [0.1       ]
 [0.10097386]
 [0.1       ]
 [0.1005    ]
 [0.101     ]
 [0.1015    ]
 [0.1015    ]
 [0.1005    ]
 [0.102     ]
 [0.101     ]
 [0.1005    ]
 [0.099     ]
 [0.1015    ]
 [0.1014    ]
 [0.101     ]
 [0.1005    ]
 [0.101     ]
 [0.102     ]
 [0.101     ]
 [0.10097386]
 [0.101     ]
 [0.1005    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.1005    ]
 [0.10097386]
 [0.101     ]
 [0.1005    ]
 [0.1005    ]
 [0.1015    ]
 [0.101     ]
 [0.1005    ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.101     ]
 [0.101     ]
 [0.102     ]
 [0.1       ]
 [0.1005    ]
 [0.1005    ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.1015    ]
 [0.1       ]
 [0.101     ]
 [0.101     ]
 [0.101     ]
 [0.1015    ]
 [0.101     ]
 [0.1015    ]
 [0.1015    ]
 [0.10

In [692]:
print(Y_test)

[[0.10097386]
 [0.1005    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1015    ]
 [0.1       ]
 [0.1       ]
 [0.1015    ]
 [0.101     ]
 [0.101     ]
 [0.1005    ]
 [0.1       ]
 [0.1015    ]
 [0.101     ]
 [0.1005    ]
 [0.101     ]
 [0.101     ]]


# Feature Scaling

In [693]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])
Y_train[:, :] = sc.fit_transform(Y_train[:, :])
Y_test[:, :] = sc.transform(Y_test[:, :])

In [694]:
print(X_train)

[[-0.08540858 -1.05622362  0.         ...  0.948894    0.20690044
  -1.03467322]
 [-0.03268278  0.03964892  0.         ...  0.74935871 -0.61120986
   1.14189308]
 [ 0.00874464  0.34343671  0.         ...  0.77283345 -0.25781404
   0.38924866]
 ...
 [-0.03833197 -1.59484124  0.         ...  0.25169423  0.41316737
  -1.71725164]
 [-0.00820294 -0.83071243  0.         ...  0.67658702  0.4729193
  -0.53517046]
 [-0.02326745 -0.13926905  0.         ...  0.22821949 -0.79312583
   0.42541175]]


In [695]:
print(X_test)

[[-2.5635214   0.19806586  0.         ... -2.30000997  0.83756976
   1.22778043]
 [ 0.0746519   1.52131331  0.         ...  0.70475671 -0.05563971
   1.53742693]
 [-0.05339649 -0.42255583  0.         ... -1.27651132  1.29675923
   0.23103512]
 ...
 [-0.30007793  0.01355671  0.         ... -0.51827723  0.11072439
   0.36212634]
 [ 0.5247043  -2.18564327  0.         ... -0.11920666  0.09148918
  -1.58164003]
 [-2.83844881 -0.4206921   0.         ...  0.14136295 -0.40044107
   0.33726421]]


In [696]:
print(Y_train)

[[ 0.98093088]
 [ 0.03569643]
 [ 0.03569643]
 [ 0.98093088]
 [ 0.03569643]
 [-0.34239735]
 [-0.90953801]
 [-0.90953801]
 [ 0.03569643]
 [-1.85477246]
 [-1.85477246]
 [-0.01371355]
 [-1.85477246]
 [-0.90953801]
 [ 0.03569643]
 [ 0.98093088]
 [ 0.98093088]
 [-0.90953801]
 [ 1.92616532]
 [ 0.03569643]
 [-0.90953801]
 [-3.74524135]
 [ 0.98093088]
 [ 0.79188399]
 [ 0.03569643]
 [-0.90953801]
 [ 0.03569643]
 [ 1.92616532]
 [ 0.03569643]
 [-0.01371355]
 [ 0.03569643]
 [-0.90953801]
 [ 0.98093088]
 [ 0.98093088]
 [ 0.98093088]
 [ 0.98093088]
 [ 0.03569643]
 [ 0.98093088]
 [ 0.03569643]
 [ 0.03569643]
 [ 0.98093088]
 [-0.90953801]
 [-0.01371355]
 [ 0.03569643]
 [-0.90953801]
 [-0.90953801]
 [ 0.98093088]
 [ 0.03569643]
 [-0.90953801]
 [ 0.98093088]
 [ 0.03569643]
 [ 0.03569643]
 [ 0.03569643]
 [ 0.03569643]
 [ 1.92616532]
 [-1.85477246]
 [-0.90953801]
 [-0.90953801]
 [ 0.98093088]
 [ 0.03569643]
 [ 0.03569643]
 [ 0.98093088]
 [ 0.98093088]
 [-1.85477246]
 [ 0.03569643]
 [ 0.03569643]
 [ 0.03569

In [697]:
print(Y_test)

[[-0.01371355]
 [-0.90953801]
 [ 0.98093088]
 [ 0.98093088]
 [ 0.98093088]
 [ 0.98093088]
 [ 0.98093088]
 [-1.85477246]
 [-1.85477246]
 [ 0.98093088]
 [ 0.03569643]
 [ 0.03569643]
 [-0.90953801]
 [-1.85477246]
 [ 0.98093088]
 [ 0.03569643]
 [-0.90953801]
 [ 0.03569643]
 [ 0.03569643]]


Low Variance Filter: Calculate the variance of all the numerical variables

In [698]:
dataset.var()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


SH1_C2_Diameter -14.020     6.191677e-07
SH1_B5_Diameter -0.220      6.616313e-08
SH1_B5_Diameter -0.160      3.108320e-08
SH1_B5_Position -0.005      2.757916e-07
SH1_B1_Width -0.190         4.480541e-08
                                ...     
SH4_D8_Distance -0.235      2.437664e-07
SH4_B7_Distance -0.148      9.221709e-08
SH4_C7_Distance -0.118      1.792112e-07
SH2_B8_Angle -5 Deg         2.523954e-05
SH2_C7_Distance -6.000_R    1.815356e-07
Length: 128, dtype: float64

High Correlation Filter

In [699]:
df=dataset.drop('SN (JOB #)', 1)
df.corr()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


SH1_C2_Diameter -14.020  SH1_B5_Diameter -0.220  \
SH1_C2_Diameter -14.020                  1.000000                0.236855   
SH1_B5_Diameter -0.220                   0.236855                1.000000   
SH1_B5_Diameter -0.160                   0.202132                0.954243   
SH1_B5_Position -0.005                   0.043446                0.315648   
SH1_B1_Width -0.190                      0.234478                0.984561   
...                                           ...                     ...   
SH4_D8_Distance -0.235                  -0.021893               -0.608491   
SH4_B7_Distance -0.148                  -0.127674               -0.567047   
SH4_C7_Distance -0.118                  -0.002433                0.037350   
SH2_B8_Angle -5 Deg                     -0.049315               -0.213918   
SH2_C7_Distance -6.000_R                 0.043954               -0.016875   

                          SH1_B5_Diameter -0.160  SH1_B5_Position -0.005  \
SH1_C2_Diameter -14.020                 0.202132                0.043446   
SH1_B5_Diameter -0.220                  0.954243                0.315648   
SH1_B5_Diameter -0.160                  1.000000                0.236856   
SH1_B5_Position -0.005                  0.236856                1.000000   
SH1_B1_Width -0.190                     0.942768                0.284504   
...                                          ...                     ...   
SH4_D8_Distance -0.235                 -0.651181               -0.203417   
SH4_B7_Distance -0.148                 -0.632631               -0.154518   
SH4_C7_Distance -0.118                  0.003163                0.215421   
SH2_B8_Angle -5 Deg                    -0.171620               -0.510653   
SH2_C7_Distance -6.000_R                0.026702                0.069473   

                          SH1_B1_Width -0.190  SH1_B1_Distance -0.200  \
SH1_C2_Diameter -14.020              0.234478                0.121288   
SH1_B5_Diameter -0.220               0.984561                0.580135   
SH1_B5_Diameter -0.160               0.942768                0.636577   
SH1_B5_Position -0.005               0.284504                0.056151   
SH1_B1_Width -0.190                  1.000000                0.600869   
...                                       ...                     ...   
SH4_D8_Distance -0.235              -0.630761               -0.404162   
SH4_B7_Distance -0.148              -0.578007               -0.228359   
SH4_C7_Distance -0.118              -0.009052                0.294344   
SH2_B8_Angle -5 Deg                 -0.193676               -0.200453   
SH2_C7_Distance -6.000_R            -0.018965               -0.079935   

                          SH1_B1_Position- 0.002  SH1_D5_Position -0.005  \
SH1_C2_Diameter -14.020                -0.161457               -0.090562   
SH1_B5_Diameter -0.220                 -0.168657               -0.351653   
SH1_B5_Diameter -0.160                 -0.047230               -0.372631   
SH1_B5_Position -0.005                  0.060427                0.270826   
SH1_B1_Width -0.190                    -0.209377               -0.348644   
...                                          ...                     ...   
SH4_D8_Distance -0.235                  0.209600                0.270203   
SH4_B7_Distance -0.148                  0.006032                0.201876   
SH4_C7_Distance -0.118                  0.193847                0.002216   
SH2_B8_Angle -5 Deg                    -0.114379               -0.141098   
SH2_C7_Distance -6.000_R               -0.049197               -0.281696   

                          SH2_D7_Width -0.190  SH2_D7_Distance -0.20  ...  \
SH1_C2_Diameter -14.020              0.269238               0.087640  ...   
SH1_B5_Diameter -0.220               0.938813               0.125861  ...   
SH1_B5_Diameter -0.160               0.878740               0.197014  ...   
SH1_B5_Position -0.005               0.297101              -0.231548  ...   
SH1_B1_Width 

# Training the Multiple Linear Regression model on the Training set

In [700]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

Predicting the Test set results

In [701]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=8)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[-1.50001172 -0.01371355]
 [ 0.07971695 -0.90953801]
 [ 4.04820599  0.98093088]
 [-1.06421082  0.98093088]
 [ 0.11374747  0.98093088]
 [ 1.13858826  0.98093088]
 [-1.2808057   0.98093088]
 [ 2.10725374 -1.85477246]
 [-0.43127944 -1.85477246]
 [-2.25078897  0.98093088]
 [-1.77210344  0.03569643]
 [ 0.77787408  0.03569643]
 [-0.44320894 -0.90953801]
 [ 2.30788184 -1.85477246]
 [-2.70831717  0.98093088]
 [ 0.19740728  0.03569643]
 [ 0.32546126 -0.90953801]
 [-1.64730942  0.03569643]
 [ 0.21840904  0.03569643]]


Getting the final linear regression equation with the values of the coefficients

In [702]:
print(regressor.coef_)
print(regressor.intercept_)

[[-6.82039517e-01  3.24522978e-02 -2.77555756e-15 -1.53023811e+00
   3.00080825e-01  4.58933241e-01 -1.11014093e+00  2.16230833e-02
   5.28237171e-01  2.84953172e-02 -2.99635105e-01  8.32682331e-01
   5.34011844e-01  2.99635105e-01  5.71669720e-01  6.51212049e-01
  -1.21838672e+00 -6.77642102e-03 -5.73715115e-01  2.88990086e-01
  -1.31954095e+00  1.40325336e+00  1.28517192e+00 -1.62565198e+00
   2.99456637e-01 -4.58511607e-01  2.42778658e-01 -8.08270887e-02
   9.76486962e-01 -6.62129195e-01 -5.71200010e-01 -1.39329296e-01
   7.95712754e-01 -9.93911067e-02 -8.17150970e-02  6.51631820e-02
  -3.42401398e-01  5.43585606e-01 -1.11070533e+00  3.24514254e-01
   2.91132109e-01  1.11989594e+00  6.20982452e-01  1.24978393e+00
   3.46707293e-01  6.75968677e-01 -9.26000540e-01  3.15699102e-01
   6.33546579e-01  8.29240820e-01 -3.94180113e-01 -7.10225697e-01
   5.74178965e-01 -1.31940759e+00  4.31315539e-01 -1.08278835e+00
  -1.55473345e-01 -4.24384764e-01  5.00055353e-01  3.71384853e-01
   9.17255

# Evaluating the Model Performance

In [703]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

-3.6365663564263544

In [704]:
from sklearn.metrics import mean_absolute_error as mae
MAE = mae(Y_test, Y_pred)
from sklearn.metrics import mean_squared_error as mse
MSE = mse(Y_test, Y_pred)

In [705]:
print(MAE)

1.7696012575796363


In [706]:
print(MSE)

4.748986324512386


In [707]:
MAPE = MAE*100
print(MAPE)

176.96012575796362
