<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate_Support_Vector_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
import io
from google.colab import files

In [3]:
uploaded = files.upload()

Saving 0041-83493_Rev07.csv to 0041-83493_Rev07.csv


In [4]:
dataset = pd.read_csv(io.BytesIO(uploaded['0041-83493_Rev07.csv']))

In [5]:
dataset

Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                            5.999452
1                    CP471589 (301514-2921-0007)  ...                            5.999395
2                    CP471589 (301514-2921-0008)  ...                            5.999445
3                    CP471589 (301514-2921-0009)  ...                            5.999580
4                    CP471589 (301514-2921-0010)  ...                            5.999311
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                            5.998685
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                            5.999750
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                            5.999499
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                            5.999586
71  CP472178 (0041-83493_07_SN 301514-3221-0070)  ...                            5.999546

[72 rows x 133 columns]

In [6]:
X = dataset.iloc[:,19: ].values
Y = dataset.iloc[:,4:5].values

In [7]:
print(X)

[[4.7000900e-01 1.0999345e+01 1.2000000e+02 ... 1.1756300e-01
  5.0414390e+00 5.9994520e+00]
 [4.7002000e-01 1.0999319e+01 1.2000000e+02 ... 1.1750800e-01
  5.0489950e+00 5.9993950e+00]
 [4.7003800e-01 1.0999267e+01 1.2000000e+02 ... 1.1744800e-01
  5.0439810e+00 5.9994450e+00]
 ...
 [4.7027800e-01 1.0999204e+01 1.2000000e+02 ... 1.1764000e-01
  5.0413440e+00 5.9994990e+00]
 [4.7026500e-01 1.0999293e+01 1.2000000e+02 ... 1.1769400e-01
  5.0405270e+00 5.9995860e+00]
 [4.7026700e-01 1.0999226e+01 1.2000000e+02 ... 1.1767000e-01
  5.0397730e+00 5.9995460e+00]]


In [8]:
print(Y)

[[0.000688]
 [0.000678]
 [0.000521]
 [0.000407]
 [0.00083 ]
 [0.00097 ]
 [0.000646]
 [0.000643]
 [0.002021]
 [0.001499]
 [0.001101]
 [0.001409]
 [0.000699]
 [0.000905]
 [0.00041 ]
 [0.000343]
 [0.000686]
 [0.000724]
 [0.000695]
 [0.000752]
 [0.001085]
 [0.0016  ]
 [0.001452]
 [0.001604]
 [0.000971]
 [0.000977]
 [0.000698]
 [0.000922]
 [0.00126 ]
 [0.001521]
 [0.001461]
 [0.001894]
 [0.000505]
 [0.000674]
 [0.000613]
 [0.000664]
 [0.00146 ]
 [0.001618]
 [0.001677]
 [0.001302]
 [0.000538]
 [0.000634]
 [0.000666]
 [0.001068]
 [0.001728]
 [0.00173 ]
 [0.001777]
 [0.001645]
 [0.00147 ]
 [0.000481]
 [0.000903]
 [0.000434]
 [0.000481]
 [0.0007  ]
 [0.00055 ]
 [0.00175 ]
 [0.0016  ]
 [0.001004]
 [0.000797]
 [0.00147 ]
 [0.000939]
 [0.001656]
 [0.002109]
 [0.001927]
 [0.001066]
 [0.000735]
 [0.00089 ]
 [0.000796]
 [0.001975]
 [0.002501]
 [0.00212 ]
 [0.002028]]


# Taking care of missing data

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:,:] = imputer.transform(X[:,:])

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Y[:,:])
Y[:,:] = imputer.transform(Y[:,:])

In [11]:
print(X)

[[4.7000900e-01 1.0999345e+01 1.2000000e+02 ... 1.1756300e-01
  5.0414390e+00 5.9994520e+00]
 [4.7002000e-01 1.0999319e+01 1.2000000e+02 ... 1.1750800e-01
  5.0489950e+00 5.9993950e+00]
 [4.7003800e-01 1.0999267e+01 1.2000000e+02 ... 1.1744800e-01
  5.0439810e+00 5.9994450e+00]
 ...
 [4.7027800e-01 1.0999204e+01 1.2000000e+02 ... 1.1764000e-01
  5.0413440e+00 5.9994990e+00]
 [4.7026500e-01 1.0999293e+01 1.2000000e+02 ... 1.1769400e-01
  5.0405270e+00 5.9995860e+00]
 [4.7026700e-01 1.0999226e+01 1.2000000e+02 ... 1.1767000e-01
  5.0397730e+00 5.9995460e+00]]


In [12]:
print(Y)

[[0.000688]
 [0.000678]
 [0.000521]
 [0.000407]
 [0.00083 ]
 [0.00097 ]
 [0.000646]
 [0.000643]
 [0.002021]
 [0.001499]
 [0.001101]
 [0.001409]
 [0.000699]
 [0.000905]
 [0.00041 ]
 [0.000343]
 [0.000686]
 [0.000724]
 [0.000695]
 [0.000752]
 [0.001085]
 [0.0016  ]
 [0.001452]
 [0.001604]
 [0.000971]
 [0.000977]
 [0.000698]
 [0.000922]
 [0.00126 ]
 [0.001521]
 [0.001461]
 [0.001894]
 [0.000505]
 [0.000674]
 [0.000613]
 [0.000664]
 [0.00146 ]
 [0.001618]
 [0.001677]
 [0.001302]
 [0.000538]
 [0.000634]
 [0.000666]
 [0.001068]
 [0.001728]
 [0.00173 ]
 [0.001777]
 [0.001645]
 [0.00147 ]
 [0.000481]
 [0.000903]
 [0.000434]
 [0.000481]
 [0.0007  ]
 [0.00055 ]
 [0.00175 ]
 [0.0016  ]
 [0.001004]
 [0.000797]
 [0.00147 ]
 [0.000939]
 [0.001656]
 [0.002109]
 [0.001927]
 [0.001066]
 [0.000735]
 [0.00089 ]
 [0.000796]
 [0.001975]
 [0.002501]
 [0.00212 ]
 [0.002028]]


## Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X = sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

In [14]:
print(X)

[[-0.10063318  0.20475078  0.         ... -0.00794881 -0.94855601
   0.13598877]
 [-0.0786162   0.1357883   0.         ... -0.1661261   0.88499876
  -0.01307584]
 [-0.04258841 -0.00213666  0.         ... -0.33868314 -0.33170897
   0.11768259]
 ...
 [ 0.43778212 -0.16923805  0.         ...  0.2134994  -0.97160891
   0.2589017 ]
 [ 0.41176205  0.06682582  0.         ...  0.36880073 -1.16986384
   0.48642137]
 [ 0.41576514 -0.11088518  0.         ...  0.29977792 -1.35283106
   0.38181463]]


In [15]:
print(Y)

[[-0.82058894]
 [-0.8395153 ]
 [-1.13665908]
 [-1.35241953]
 [-0.55183469]
 [-0.28686572]
 [-0.90007963]
 [-0.90575754]
 [ 1.70229424]
 [ 0.71433848]
 [-0.03893046]
 [ 0.54400129]
 [-0.79976995]
 [-0.40988703]
 [-1.34674162]
 [-1.4735482 ]
 [-0.82437421]
 [-0.75245406]
 [-0.80734049]
 [-0.69946027]
 [-0.06921263]
 [ 0.90549467]
 [ 0.62538461]
 [ 0.91306522]
 [-0.28497308]
 [-0.27361727]
 [-0.80166259]
 [-0.37771222]
 [ 0.26199859]
 [ 0.75597647]
 [ 0.64241833]
 [ 1.46192952]
 [-1.16694125]
 [-0.84708584]
 [-0.96253661]
 [-0.86601219]
 [ 0.6405257 ]
 [ 0.93956211]
 [ 1.05122761]
 [ 0.34148928]
 [-1.10448427]
 [-0.92279126]
 [-0.86222692]
 [-0.10138743]
 [ 1.14775202]
 [ 1.15153729]
 [ 1.24049117]
 [ 0.99066327]
 [ 0.65945205]
 [-1.2123645 ]
 [-0.4136723 ]
 [-1.30131837]
 [-1.2123645 ]
 [-0.79787731]
 [-1.08177265]
 [ 1.18939001]
 [ 0.90549467]
 [-0.22251611]
 [-0.61429167]
 [ 0.65945205]
 [-0.34553742]
 [ 1.01148226]
 [ 1.86884617]
 [ 1.5243865 ]
 [-0.10517271]
 [-0.73163507]
 [-0.43827

## Training the SVR model on the whole dataset

In [16]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, Y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Predicting the test results

In [17]:
Y_pred = regressor.predict(X)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y.reshape(len(Y),1)),1))

[[-0.72 -0.82]
 [-0.94 -0.84]
 [-1.04 -1.14]
 [-1.04 -1.35]
 [-0.49 -0.55]
 [-0.39 -0.29]
 [-0.8  -0.9 ]
 [-0.81 -0.91]
 [ 1.03  1.7 ]
 [ 0.61  0.71]
 [-0.06 -0.04]
 [ 0.44  0.54]
 [-0.64 -0.8 ]
 [-0.54 -0.41]
 [-1.14 -1.35]
 [-1.37 -1.47]
 [-0.72 -0.82]
 [-0.76 -0.75]
 [-0.71 -0.81]
 [-0.6  -0.7 ]
 [ 0.03 -0.07]
 [ 0.81  0.91]
 [ 0.53  0.63]
 [ 0.81  0.91]
 [-0.39 -0.28]
 [-0.63 -0.27]
 [-0.7  -0.8 ]
 [-0.3  -0.38]
 [ 0.36  0.26]
 [ 0.66  0.76]
 [ 0.65  0.64]
 [ 0.96  1.46]
 [-0.82 -1.17]
 [-0.75 -0.85]
 [-0.86 -0.96]
 [-0.77 -0.87]
 [ 0.74  0.64]
 [ 0.84  0.94]
 [ 1.05  1.05]
 [ 0.4   0.34]
 [-1.   -1.1 ]
 [-0.97 -0.92]
 [-0.86 -0.86]
 [-0.2  -0.1 ]
 [ 1.05  1.15]
 [ 1.05  1.15]
 [ 1.14  1.24]
 [ 0.89  0.99]
 [ 0.56  0.66]
 [-1.11 -1.21]
 [-0.69 -0.41]
 [-1.01 -1.3 ]
 [-1.1  -1.21]
 [-0.7  -0.8 ]
 [-0.98 -1.08]
 [ 1.01  1.19]
 [ 0.81  0.91]
 [-0.3  -0.22]
 [-0.58 -0.61]
 [ 0.56  0.66]
 [-0.24 -0.35]
 [ 1.11  1.01]
 [ 1.77  1.87]
 [ 1.42  1.52]
 [-0.01 -0.11]
 [-0.48 -0.73]
 [-0.42 -0

In [18]:
print(regressor.coef_)
print(regressor.intercept_)

AttributeError: ignored

# Evaluating the Model Performance

In [19]:
from sklearn.metrics import r2_score
r2_score(Y, Y_pred)

0.9682096594103734