<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate_Support_Vector_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Regression (SVR)

## Importing the libraries

In [401]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [402]:
import io
from google.colab import files

In [403]:
uploaded = files.upload()

Saving 0041-83493_Rev07.csv to 0041-83493_Rev07 (18).csv


In [404]:
dataset = pd.read_csv(io.BytesIO(uploaded['0041-83493_Rev07.csv']))

In [405]:
dataset

SN (JOB #)  SH1_C2_Diameter -14.020  \
0              IPI-001_SN0001 (CP467059)                14.017400   
1               0 DEG SN 0002 (CP471589)                14.016011   
2              90 DEG SN 0003 (CP471589)                14.015942   
3             180 DEG SN 0004 (CP471589)                14.018477   
4               SN0005 270DEG (CP471589)                14.016071   
..                                   ...                      ...   
87  SN 301514-5021-0256 (CP474149_REV08)                14.015503   
88  SN 301514-5021-0257 (CP474149_REV08)                14.015220   
89  SN 301514-5021-0258 (CP474149_REV08)                14.015178   
90  SN 301514-5021-0259 (CP474149_REV08)                14.017048   
91  SN 301514-5021-0260 (CP474149_REV08)                14.017311   

    SH1_B5_Diameter -0.220  SH1_B5_Diameter -0.160  SH1_B5_Position -0.005  \
0                 0.222300                0.161250                0.000700   
1                 0.221733                0.161174                0.000481   
2                 0.221904                0.161202                0.000903   
3                 0.221841                0.161174                0.000434   
4                 0.221928                0.161158                0.000481   
..                     ...                     ...                     ...   
87                0.221326                0.160738                0.000396   
88                0.221238                0.160695                0.001317   
89                0.221296                0.160680                0.000526   
90                0.221358                0.160751                0.000183   
91                0.221343                0.160738                0.000401   

    SH1_B1_Width -0.190  SH1_B1_Distance -0.200  SH1_B1_Position- 0.002  \
0              0.192200                0.198800                0.000000   
1              0.191812                0.200574                0.000000   
2              0.191788                0.200091                0.000000   
3              0.191770                0.200465                0.000000   
4              0.191820                0.200294                0.000000   
..                  ...                     ...                     ...   
87             0.191336                0.200956                0.000008   
88             0.191349                0.200278                0.000000   
89             0.191342                0.200183                0.000000   
90             0.191340                0.200260                0.000000   
91             0.191361                0.200214                0.000000   

    SH1_D5_Position -0.005  SH2_D7_Width -0.190  ...  SH4_B7_Width -0.065  \
0                 0.001100             0.192200  ...             0.068400   
1                 0.001154             0.191750  ...             0.067757   
2                 0.001015             0.191730  ...             0.067760   
3                 0.001113             0.191971  ...             0.067707   
4                 0.000876             0.191710  ...             0.067761   
..                     ...                  ...  ...                  ...   
87                0.001500             0.191257  ...             0.067776   
88                0.001034             0.191284  ...             0.067780   
89                0.000821             0.191169  ...             0.067780   
90                0.000817             0.191211  ...             0.067777   
91                0.001026             0.191211  ...             0.067797   

    SH3_B8_Position -0.005  SH3_B7_Distance -0.100  SH4_C7_Radius -0.0325  \
0                 0.001200                0.098950               0.033800   
1                 0.002455                0.102773               0.033507   
2                 0.001692                0.102942               0.033518   
3                 0.002165                0.102567               0.033509   
4                 0.001043                0.102188   

In [406]:
X = dataset.iloc[:,19: ].values
Y = dataset.iloc[:,18:19].values

In [407]:
print(X)

[[4.718250e-01 1.100090e+01 1.200000e+02 ... 1.172500e-01 5.040300e+00
  6.000200e+00]
 [4.688300e-01 1.099946e+01 1.200000e+02 ... 1.174120e-01 5.056671e+00
  6.000013e+00]
 [4.688470e-01 1.099950e+01 1.200000e+02 ... 1.174690e-01 5.050116e+00
  5.999963e+00]
 ...
 [4.705320e-01 1.100038e+01 1.200000e+02 ... 1.186400e-01 5.044763e+00
  6.000126e+00]
 [4.705440e-01 1.100095e+01 1.200000e+02 ... 1.185080e-01 5.046067e+00
  6.000382e+00]
 [4.705360e-01 1.100068e+01 1.200000e+02 ... 1.186860e-01 5.046220e+00
  6.000193e+00]]


In [408]:
print(Y)

[[   nan]
 [   nan]
 [   nan]
 [   nan]
 [0.099 ]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1005]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1005]
 [0.1015]
 [0.1015]
 [0.1014]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.1005]
 [0.1005]
 [0.101 ]
 [0.1005]
 [0.1005]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.1005]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1005]
 [0.1005]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1005]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.1005]
 [0.101 ]
 [0.1015]
 [0.1005]
 [0.1015]
 [0.1015]
 [0.1005]
 [0.1015]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.1015]
 [0.101 ]
 [0.1015]
 [0.1015]
 [0.1015]
 [0.101 ]
 [0.1   ]
 [0.1   ]
 [0.1   ]
 [0.1005]
 [0.1005]
 [0.101 ]
 [0.1   ]
 [0.1008]
 [0.1005]
 [0.1   ]
 [0.1   ]
 [0.1   ]
 [0.1005]
 [0.101 ]
 [0.1   ]
 [0.102 ]
 [0.102 ]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.101 ]
 [0.102 ]]


# Taking care of missing data

In [409]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:,:] = imputer.transform(X[:,:])

In [410]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Y[:,:])
Y[:,:] = imputer.transform(Y[:,:])

In [411]:
print(X)

[[4.718250e-01 1.100090e+01 1.200000e+02 ... 1.172500e-01 5.040300e+00
  6.000200e+00]
 [4.688300e-01 1.099946e+01 1.200000e+02 ... 1.174120e-01 5.056671e+00
  6.000013e+00]
 [4.688470e-01 1.099950e+01 1.200000e+02 ... 1.174690e-01 5.050116e+00
  5.999963e+00]
 ...
 [4.705320e-01 1.100038e+01 1.200000e+02 ... 1.186400e-01 5.044763e+00
  6.000126e+00]
 [4.705440e-01 1.100095e+01 1.200000e+02 ... 1.185080e-01 5.046067e+00
  6.000382e+00]
 [4.705360e-01 1.100068e+01 1.200000e+02 ... 1.186860e-01 5.046220e+00
  6.000193e+00]]


In [412]:
print(Y)

[[0.100974]
 [0.100974]
 [0.100974]
 [0.100974]
 [0.099   ]
 [0.101   ]
 [0.1015  ]
 [0.101   ]
 [0.1005  ]
 [0.1015  ]
 [0.1015  ]
 [0.1015  ]
 [0.1015  ]
 [0.1015  ]
 [0.1005  ]
 [0.1015  ]
 [0.1015  ]
 [0.1014  ]
 [0.1015  ]
 [0.101   ]
 [0.101   ]
 [0.101   ]
 [0.1015  ]
 [0.1015  ]
 [0.1015  ]
 [0.1005  ]
 [0.1005  ]
 [0.101   ]
 [0.1005  ]
 [0.1005  ]
 [0.1015  ]
 [0.101   ]
 [0.101   ]
 [0.1005  ]
 [0.101   ]
 [0.1015  ]
 [0.101   ]
 [0.1005  ]
 [0.1005  ]
 [0.101   ]
 [0.101   ]
 [0.101   ]
 [0.1015  ]
 [0.101   ]
 [0.1005  ]
 [0.101   ]
 [0.1015  ]
 [0.101   ]
 [0.101   ]
 [0.1015  ]
 [0.1015  ]
 [0.101   ]
 [0.101   ]
 [0.1005  ]
 [0.101   ]
 [0.1015  ]
 [0.1005  ]
 [0.1015  ]
 [0.1015  ]
 [0.1005  ]
 [0.1015  ]
 [0.101   ]
 [0.101   ]
 [0.101   ]
 [0.1015  ]
 [0.101   ]
 [0.1015  ]
 [0.1015  ]
 [0.1015  ]
 [0.101   ]
 [0.1     ]
 [0.1     ]
 [0.1     ]
 [0.1005  ]
 [0.1005  ]
 [0.101   ]
 [0.1     ]
 [0.1008  ]
 [0.1005  ]
 [0.1     ]
 [0.1     ]
 [0.1     ]
 [0.1005  ]
 [0.

## Feature Scaling

In [413]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X = sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

In [414]:
print(X)

[[ 3.130218e+00  2.980553e+00  0.000000e+00 ... -2.774663e+00
  -1.153025e+00  1.831175e+00]
 [-2.592999e+00  1.852023e-01  0.000000e+00 ... -2.389889e+00
   2.123457e+00  1.389875e+00]
 [-2.560514e+00  2.493961e-01  0.000000e+00 ... -2.254506e+00
   8.115434e-01  1.271880e+00]
 ...
 [ 6.593934e-01  1.959287e+00  0.000000e+00 ...  5.267923e-01
  -2.598026e-01  1.656542e+00]
 [ 6.823245e-01  3.085598e+00  0.000000e+00 ...  2.132728e-01
   1.179082e-03  2.260675e+00]
 [ 6.670371e-01  2.544813e+00  0.000000e+00 ...  6.360491e-01
   3.180040e-02  1.814655e+00]]


In [415]:
print(Y)

[[-2.616068e-14]
 [-2.616068e-14]
 [-2.616068e-14]
 [-2.616068e-14]
 [-3.720883e+00]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [-8.932689e-01]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [-8.932689e-01]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [ 8.032994e-01]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [-8.932689e-01]
 [-8.932689e-01]
 [ 4.926903e-02]
 [-8.932689e-01]
 [-8.932689e-01]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [-8.932689e-01]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [-8.932689e-01]
 [-8.932689e-01]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [-8.932689e-01]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [ 9.918070e-01]
 [ 4.926903e-02]
 [ 4.926903e-02]
 [-8.932689e-01]
 [ 4.926903e-02]
 [ 9.918070e-01]
 [-8.932689e-01]
 [ 9.918070e-01]
 [ 9.918070e-0

## Training the SVR model on the whole dataset

In [416]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, Y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Predicting the test results

In [417]:
Y_pred = regressor.predict(X)
np.set_printoptions(precision=6)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y.reshape(len(Y),1)),1))

[[-1.001567e-01 -2.616068e-14]
 [-1.000959e-01 -2.616068e-14]
 [-1.001694e-01 -2.616068e-14]
 [-7.853559e-02 -2.616068e-14]
 [-8.483888e-01 -3.720883e+00]
 [-6.401969e-03  4.926903e-02]
 [ 7.265033e-01  9.918070e-01]
 [ 1.495938e-01  4.926903e-02]
 [ 1.247454e-01 -8.932689e-01]
 [ 9.715389e-01  9.918070e-01]
 [ 8.915437e-01  9.918070e-01]
 [ 8.920915e-01  9.918070e-01]
 [ 9.255106e-01  9.918070e-01]
 [ 8.918249e-01  9.918070e-01]
 [ 4.177221e-01 -8.932689e-01]
 [ 8.717731e-01  9.918070e-01]
 [ 8.917646e-01  9.918070e-01]
 [ 6.040419e-01  8.032994e-01]
 [ 8.918574e-01  9.918070e-01]
 [ 6.272830e-01  4.926903e-02]
 [ 2.097710e-01  4.926903e-02]
 [ 4.973655e-01  4.926903e-02]
 [ 8.919887e-01  9.918070e-01]
 [ 7.182248e-01  9.918070e-01]
 [ 8.213839e-01  9.918070e-01]
 [-7.930494e-01 -8.932689e-01]
 [-4.176308e-01 -8.932689e-01]
 [-5.078814e-02  4.926903e-02]
 [-2.685314e-01 -8.932689e-01]
 [-2.012507e-01 -8.932689e-01]
 [ 2.139595e-01  9.918070e-01]
 [ 6.609295e-02  4.926903e-02]
 [-5.075

# Evaluating the Model Performance

In [418]:
from sklearn.metrics import r2_score
r2_score(Y, Y_pred)

0.6326013097657898

In [419]:
from sklearn.metrics import mean_absolute_error as mae
MAE = mae(Y, Y_pred)
from sklearn.metrics import mean_squared_error as mse
MSE = mse(Y, Y_pred)

In [420]:
print(MAE)

0.389046626262801


In [421]:
print(MSE)

0.3673986902342102


In [422]:
MAPE = MAE*100
print(MAPE)

38.9046626262801
