<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate_MultipleLinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# Importing the dataset

In [2]:
import io
from google.colab import files

In [3]:
uploaded = files.upload()

Saving 0041-83493_Rev07.csv to 0041-83493_Rev07.csv


In [4]:
dataset = pd.read_csv(io.BytesIO(uploaded['0041-83493_Rev07.csv']))

In [5]:
dataset

Job #  ...  6.000_R +/-0.005 (SH2_C7_Distance)
0                    CP471589 (301514-2921-0006)  ...                            5.999452
1                    CP471589 (301514-2921-0007)  ...                            5.999395
2                    CP471589 (301514-2921-0008)  ...                            5.999445
3                    CP471589 (301514-2921-0009)  ...                            5.999580
4                    CP471589 (301514-2921-0010)  ...                            5.999311
..                                           ...  ...                                 ...
67  CP472178 (0041-83493_07_SN 301514-3221-0066)  ...                            5.998685
68  CP472178 (0041-83493_07_SN 301514-3221-0067)  ...                            5.999750
69  CP472178 (0041-83493_07_SN 301514-3221-0068)  ...                            5.999499
70  CP472178 (0041-83493_07_SN 301514-3221-0069)  ...                            5.999586
71  CP472178 (0041-83493_07_SN 301514-3221-0070)  ...                            5.999546

[72 rows x 133 columns]

In [6]:
X = dataset.iloc[:,19: ].values
Y = dataset.iloc[:,4:5].values

In [7]:
print(X)

[[4.7000900e-01 1.0999345e+01 1.2000000e+02 ... 1.1756300e-01
  5.0414390e+00 5.9994520e+00]
 [4.7002000e-01 1.0999319e+01 1.2000000e+02 ... 1.1750800e-01
  5.0489950e+00 5.9993950e+00]
 [4.7003800e-01 1.0999267e+01 1.2000000e+02 ... 1.1744800e-01
  5.0439810e+00 5.9994450e+00]
 ...
 [4.7027800e-01 1.0999204e+01 1.2000000e+02 ... 1.1764000e-01
  5.0413440e+00 5.9994990e+00]
 [4.7026500e-01 1.0999293e+01 1.2000000e+02 ... 1.1769400e-01
  5.0405270e+00 5.9995860e+00]
 [4.7026700e-01 1.0999226e+01 1.2000000e+02 ... 1.1767000e-01
  5.0397730e+00 5.9995460e+00]]


In [8]:
print(Y)

[[0.000688]
 [0.000678]
 [0.000521]
 [0.000407]
 [0.00083 ]
 [0.00097 ]
 [0.000646]
 [0.000643]
 [0.002021]
 [0.001499]
 [0.001101]
 [0.001409]
 [0.000699]
 [0.000905]
 [0.00041 ]
 [0.000343]
 [0.000686]
 [0.000724]
 [0.000695]
 [0.000752]
 [0.001085]
 [0.0016  ]
 [0.001452]
 [0.001604]
 [0.000971]
 [0.000977]
 [0.000698]
 [0.000922]
 [0.00126 ]
 [0.001521]
 [0.001461]
 [0.001894]
 [0.000505]
 [0.000674]
 [0.000613]
 [0.000664]
 [0.00146 ]
 [0.001618]
 [0.001677]
 [0.001302]
 [0.000538]
 [0.000634]
 [0.000666]
 [0.001068]
 [0.001728]
 [0.00173 ]
 [0.001777]
 [0.001645]
 [0.00147 ]
 [0.000481]
 [0.000903]
 [0.000434]
 [0.000481]
 [0.0007  ]
 [0.00055 ]
 [0.00175 ]
 [0.0016  ]
 [0.001004]
 [0.000797]
 [0.00147 ]
 [0.000939]
 [0.001656]
 [0.002109]
 [0.001927]
 [0.001066]
 [0.000735]
 [0.00089 ]
 [0.000796]
 [0.001975]
 [0.002501]
 [0.00212 ]
 [0.002028]]


In [9]:
dataset.shape

(72, 133)

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Columns: 133 entries, Job # to 6.000_R +/-0.005 (SH2_C7_Distance)
dtypes: float64(131), int64(1), object(1)
memory usage: 74.9+ KB


# Taking care of missing data

Impute Missing Values. 

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:,:] = imputer.transform(X[:,:])

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Y[:,:])
Y[:,:] = imputer.transform(Y[:,:])

In [13]:
print(X)

[[4.7000900e-01 1.0999345e+01 1.2000000e+02 ... 1.1756300e-01
  5.0414390e+00 5.9994520e+00]
 [4.7002000e-01 1.0999319e+01 1.2000000e+02 ... 1.1750800e-01
  5.0489950e+00 5.9993950e+00]
 [4.7003800e-01 1.0999267e+01 1.2000000e+02 ... 1.1744800e-01
  5.0439810e+00 5.9994450e+00]
 ...
 [4.7027800e-01 1.0999204e+01 1.2000000e+02 ... 1.1764000e-01
  5.0413440e+00 5.9994990e+00]
 [4.7026500e-01 1.0999293e+01 1.2000000e+02 ... 1.1769400e-01
  5.0405270e+00 5.9995860e+00]
 [4.7026700e-01 1.0999226e+01 1.2000000e+02 ... 1.1767000e-01
  5.0397730e+00 5.9995460e+00]]


In [14]:
print(Y)

[[0.000688]
 [0.000678]
 [0.000521]
 [0.000407]
 [0.00083 ]
 [0.00097 ]
 [0.000646]
 [0.000643]
 [0.002021]
 [0.001499]
 [0.001101]
 [0.001409]
 [0.000699]
 [0.000905]
 [0.00041 ]
 [0.000343]
 [0.000686]
 [0.000724]
 [0.000695]
 [0.000752]
 [0.001085]
 [0.0016  ]
 [0.001452]
 [0.001604]
 [0.000971]
 [0.000977]
 [0.000698]
 [0.000922]
 [0.00126 ]
 [0.001521]
 [0.001461]
 [0.001894]
 [0.000505]
 [0.000674]
 [0.000613]
 [0.000664]
 [0.00146 ]
 [0.001618]
 [0.001677]
 [0.001302]
 [0.000538]
 [0.000634]
 [0.000666]
 [0.001068]
 [0.001728]
 [0.00173 ]
 [0.001777]
 [0.001645]
 [0.00147 ]
 [0.000481]
 [0.000903]
 [0.000434]
 [0.000481]
 [0.0007  ]
 [0.00055 ]
 [0.00175 ]
 [0.0016  ]
 [0.001004]
 [0.000797]
 [0.00147 ]
 [0.000939]
 [0.001656]
 [0.002109]
 [0.001927]
 [0.001066]
 [0.000735]
 [0.00089 ]
 [0.000796]
 [0.001975]
 [0.002501]
 [0.00212 ]
 [0.002028]]


Check the percentage of missing values in each variable.

In [15]:
dataset.isnull().sum()/len(dataset)*100

Job #                                    0.0
14.020 +0.0/-0.005 (SH1_C2_Diameter)     0.0
0.220 +0.005/-0.0 (SH1_B5_Diameter)      0.0
0.160 +/- 0.002 (SH1_B5_Diameter)        0.0
0.005 +0.0/-0.005 (SH1_B5_Position)      0.0
                                        ... 
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)    0.0
0.118 +/-0.005 (SH4_C7_Distance_1_Z)     0.0
0.118 +/-0.005 (SH4_C7_Distance_2_Y)     0.0
5 Deg +/- 1 (SH2_B8_Angle)               0.0
6.000_R +/-0.005 (SH2_C7_Distance)       0.0
Length: 133, dtype: float64

# Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [17]:
print(X_train)

[[4.7045000e-01 1.0999100e+01 1.2000000e+02 ... 1.1700000e-01
  5.0372000e+00 5.9988000e+00]
 [4.7026500e-01 1.0999293e+01 1.2000000e+02 ... 1.1769400e-01
  5.0405270e+00 5.9995860e+00]
 [4.7026200e-01 1.0999231e+01 1.2000000e+02 ... 1.1725000e-01
  5.0395230e+00 5.9997270e+00]
 ...
 [4.7020700e-01 1.0998803e+01 1.2000000e+02 ... 1.1751000e-01
  5.0475390e+00 5.9986700e+00]
 [4.6869700e-01 1.0999290e+01 1.2000000e+02 ... 1.1767300e-01
  5.0420030e+00 5.9993050e+00]
 [4.6869900e-01 1.0999235e+01 1.2000000e+02 ... 1.1778000e-01
  5.0471200e+00 5.9993040e+00]]


In [18]:
print(X_test)

[[4.7017400e-01 1.0998912e+01 1.2000000e+02 ... 1.1776000e-01
  5.0472130e+00 5.9993000e+00]
 [4.7016400e-01 1.0998939e+01 1.2000000e+02 ... 1.1781100e-01
  5.0423880e+00 5.9993030e+00]
 [4.7026700e-01 1.0998638e+01 1.2000000e+02 ... 1.1785700e-01
  5.0528480e+00 5.9986220e+00]
 ...
 [4.7026800e-01 1.0999551e+01 1.2000000e+02 ... 1.1784000e-01
  5.0427570e+00 5.9997230e+00]
 [4.7020400e-01 1.0998944e+01 1.2000000e+02 ... 1.1772900e-01
  5.0483340e+00 5.9991830e+00]
 [4.7014500e-01 1.0998803e+01 1.2000000e+02 ... 1.1773100e-01
  5.0457630e+00 5.9991090e+00]]


In [19]:
print(Y_train)

[[0.00175 ]
 [0.00212 ]
 [0.002109]
 [0.001068]
 [0.00083 ]
 [0.000735]
 [0.000903]
 [0.000521]
 [0.000538]
 [0.001409]
 [0.000407]
 [0.00055 ]
 [0.00173 ]
 [0.001101]
 [0.000634]
 [0.000481]
 [0.0007  ]
 [0.001004]
 [0.000505]
 [0.00041 ]
 [0.002501]
 [0.000752]
 [0.001521]
 [0.000481]
 [0.000664]
 [0.000695]
 [0.000688]
 [0.000343]
 [0.00097 ]
 [0.000686]
 [0.001085]
 [0.00089 ]
 [0.002021]
 [0.000905]
 [0.000977]
 [0.001618]
 [0.000724]
 [0.000939]
 [0.001777]
 [0.001927]
 [0.001302]
 [0.001677]
 [0.000678]
 [0.000797]
 [0.000699]
 [0.001656]
 [0.000971]
 [0.000646]
 [0.001604]
 [0.00146 ]
 [0.0016  ]
 [0.001499]
 [0.001975]
 [0.000796]
 [0.001066]
 [0.001645]
 [0.001728]]


In [20]:
print(Y_test)

[[0.000698]
 [0.000922]
 [0.00147 ]
 [0.001452]
 [0.001461]
 [0.000434]
 [0.000643]
 [0.00147 ]
 [0.000613]
 [0.002028]
 [0.0016  ]
 [0.00126 ]
 [0.001894]
 [0.000666]
 [0.000674]]


# Feature Scaling

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])
Y_train[:, :] = sc.fit_transform(Y_train[:, :])
Y_test[:, :] = sc.transform(Y_test[:, :])

In [22]:
print(X_train)

[[ 0.77256338 -0.50416167  0.         ... -1.47332913 -1.9621983
  -1.73617281]
 [ 0.42383341  0.03197004  0.         ...  0.46140576 -1.12236459
   0.47284725]
 [ 0.41817833 -0.1402588   0.         ... -0.77637852 -1.37580404
   0.86912183]
 ...
 [ 0.31450185 -1.32919338  0.         ... -0.05154989  0.64767269
  -2.10153236]
 [-2.53188872  0.02363639  0.         ...  0.40286191 -0.7497783
  -0.31689148]
 [-2.52811867 -0.12914726  0.         ...  0.70115677  0.54190463
  -0.31970193]]


In [23]:
print(X_test)

[[ 0.25229596 -1.02640397  0.         ...  0.64540072  0.5653806
  -0.33094377]
 [ 0.2334457  -0.95140108  0.         ...  0.78757864 -0.65259286
  -0.32251239]
 [ 0.42760346 -1.78754433  0.         ...  0.91581756  1.98782214
  -2.23643434]
 ...
 [ 0.42948849  0.74866425  0.         ...  0.86842491 -0.55944629
   0.85788   ]
 [ 0.30884677 -0.93751166  0.         ...  0.55897884  0.84835433
  -0.65976736]
 [ 0.19763019 -1.32919338  0.         ...  0.56455445  0.19935749
  -0.86774126]]


In [24]:
print(Y_train)

[[ 1.18756896]
 [ 1.87787901]
 [ 1.85735628]
 [-0.08484038]
 [-0.52887766]
 [-0.70611943]
 [-0.39268135]
 [-1.10537984]
 [-1.07366289]
 [ 0.55136429]
 [-1.31806996]
 [-1.05127446]
 [ 1.1502549 ]
 [-0.02327219]
 [-0.89455542]
 [-1.18000795]
 [-0.77141903]
 [-0.20424536]
 [-1.13523108]
 [-1.31247286]
 [ 2.5887118 ]
 [-0.67440248]
 [ 0.76032301]
 [-1.18000795]
 [-0.83858433]
 [-0.78074754]
 [-0.79380746]
 [-1.43747495]
 [-0.26767926]
 [-0.79753887]
 [-0.05312343]
 [-0.41693549]
 [ 1.69317443]
 [-0.38894995]
 [-0.25461934]
 [ 0.94129618]
 [-0.72664216]
 [-0.32551605]
 [ 1.23794294]
 [ 1.51779836]
 [ 0.35173408]
 [ 1.05137265]
 [-0.81246449]
 [-0.59044585]
 [-0.77328473]
 [ 1.01219289]
 [-0.26581356]
 [-0.87216698]
 [ 0.91517634]
 [ 0.64651513]
 [ 0.90771353]
 [ 0.71927754]
 [ 1.6073521 ]
 [-0.59231156]
 [-0.08857179]
 [ 0.99167016]
 [ 1.1465235 ]]


In [25]:
print(Y_test)

[[-0.77515044]
 [-0.357233  ]
 [ 0.66517216]
 [ 0.63158951]
 [ 0.64838084]
 [-1.26769599]
 [-0.87776409]
 [ 0.66517216]
 [-0.93373518]
 [ 1.70623435]
 [ 0.90771353]
 [ 0.27337456]
 [ 1.45623017]
 [-0.83485293]
 [-0.8199273 ]]


Low Variance Filter: Calculate the variance of all the numerical variables

In [26]:
dataset.var()

14.020 +0.0/-0.005 (SH1_C2_Diameter)     5.749342e-07
0.220 +0.005/-0.0 (SH1_B5_Diameter)      6.010280e-09
0.160 +/- 0.002 (SH1_B5_Diameter)        3.067319e-09
0.005 +0.0/-0.005 (SH1_B5_Position)      2.831002e-07
0.190 +0.002/-0.0 (SH1_B1_Width)         5.213488e-09
                                             ...     
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)    2.549214e-08
0.118 +/-0.005 (SH4_C7_Distance_1_Z)     4.272229e-07
0.118 +/-0.005 (SH4_C7_Distance_2_Y)     1.226059e-07
5 Deg +/- 1 (SH2_B8_Angle)               1.722147e-05
6.000_R +/-0.005 (SH2_C7_Distance)       1.482773e-07
Length: 132, dtype: float64

High Correlation Filter

In [27]:
df=dataset.drop('Job #', 1)
df.corr()

14.020 +0.0/-0.005 (SH1_C2_Diameter)  ...  6.000_R +/-0.005 (SH2_C7_Distance)
14.020 +0.0/-0.005 (SH1_C2_Diameter)                               1.000000  ...                            0.002511
0.220 +0.005/-0.0 (SH1_B5_Diameter)                                0.207466  ...                           -0.035076
0.160 +/- 0.002 (SH1_B5_Diameter)                                 -0.088545  ...                            0.230778
0.005 +0.0/-0.005 (SH1_B5_Position)                               -0.000929  ...                            0.104001
0.190 +0.002/-0.0 (SH1_B1_Width)                                   0.256207  ...                           -0.054577
...                                                                     ...  ...                                 ...
0.148 +/- 0.005 (SH4_B7_Distance_2_Z)                             -0.000387  ...                           -0.005786
0.118 +/-0.005 (SH4_C7_Distance_1_Z)                              -0.147150  ...                           -0.357836
0.118 +/-0.005 (SH4_C7_Distance_2_Y)                              -0.063113  ...                           -0.323452
5 Deg +/- 1 (SH2_B8_Angle)                                        -0.235347  ...                           -0.169645
6.000_R +/-0.005 (SH2_C7_Distance)                                 0.002511  ...                            1.000000

[132 rows x 132 columns]

# Training the Multiple Linear Regression model on the Training set

In [28]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

Predicting the Test set results

In [29]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=8)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[ 0.26163846 -0.77515044]
 [-0.29735373 -0.357233  ]
 [-0.67747796  0.66517216]
 [ 0.72628006  0.63158951]
 [ 0.55884419  0.64838084]
 [-0.0603228  -1.26769599]
 [-0.28223865 -0.87776409]
 [-0.86620835  0.66517216]
 [-0.25850784 -0.93373518]
 [ 1.64864391  1.70623435]
 [ 0.40805619  0.90771353]
 [ 0.72275206  0.27337456]
 [ 0.70349203  1.45623017]
 [-0.40648678 -0.83485293]
 [-0.2015944  -0.8199273 ]]


Getting the final linear regression equation with the values of the coefficients

In [30]:
print(regressor.coef_)
print(regressor.intercept_)

[[ 0.0090157   0.14364064  0.00534404 -0.26452911  0.05637893  0.02218798
  -0.26910061 -0.21894003 -0.16395038 -0.0601472  -0.05769637 -0.01926348
   0.0922609  -0.09209891 -0.05401453  0.08773212 -0.10619085  0.14720538
  -0.03531163  0.0492198   0.04408493 -0.04181226  0.09795595 -0.01634362
   0.08168544  0.182642   -0.11420107 -0.00970945 -0.12616363 -0.24337942
  -0.06163299 -0.07198104  0.08805948 -0.06846686  0.04375775 -0.30017232
   0.09789178 -0.00129065  0.01428845 -0.21445033 -0.05741719  0.07585485
  -0.07896946 -0.05958279  0.12355512 -0.00331721  0.01335426  0.09934805
   0.05702231 -0.23374772  0.172372    0.19437801 -0.00914009  0.01714208
  -0.04419777 -0.07527238 -0.03895656 -0.02599902 -0.10324388 -0.22540018
   0.11927845  0.01448405  0.12448667  0.03458252 -0.06237101 -0.02003361
  -0.04832586 -0.01507539 -0.02874248 -0.01602324 -0.03918742 -0.01364709
   0.05303365 -0.02443044 -0.0946689  -0.10543992  0.03564268 -0.11789615
   0.02532447  0.07091422 -0.00538343 

# Evaluating the Model Performance

In [31]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.29481302730648995