<a href="https://colab.research.google.com/github/MananDesai2997/MananDesai2997/blob/main/RexolitePlate_support_vector_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Regression (SVR)

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [4]:
dataset = pd.read_csv('0041 83493 Rev07.csv')
X = dataset.iloc[:,19: ].values
Y = dataset.iloc[:, 1:2].values

In [5]:
print(X)

[[4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0490e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1700e-01 5.0440e+00 5.9990e+00]
 ...
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 6.0000e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0400e+00 6.0000e+00]]


In [6]:
print(Y)

[[14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.018]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.018]
 [14.016]
 [14.017]
 [14.018]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.018]
 [14.017]
 [14.016]
 [14.018]
 [14.017]]


# Taking care of missing data

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, :])
X[:,:] = imputer.transform(X[:,:])

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Y[:,:])
Y[:,:] = imputer.transform(Y[:,:])

In [9]:
print(X)

[[4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0490e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1700e-01 5.0440e+00 5.9990e+00]
 ...
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 5.9990e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0410e+00 6.0000e+00]
 [4.7000e-01 1.0999e+01 1.2000e+02 ... 1.1800e-01 5.0400e+00 6.0000e+00]]


In [10]:
print(Y)

[[14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.018]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.018]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.016]
 [14.017]
 [14.016]
 [14.017]
 [14.017]
 [14.016]
 [14.016]
 [14.018]
 [14.016]
 [14.017]
 [14.018]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.017]
 [14.017]
 [14.019]
 [14.017]
 [14.017]
 [14.019]
 [14.018]
 [14.017]
 [14.016]
 [14.018]
 [14.017]]


## Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_Y = StandardScaler()
X = sc_X.fit_transform(X)
Y = sc_Y.fit_transform(Y)

In [12]:
print(X)

[[ 0.20851441 -0.51753318  0.         ...  0.68836315 -1.04842119
  -0.82122993]
 [ 0.20851441 -0.51753318  0.         ...  0.68836315  0.88712562
  -0.82122993]
 [ 0.20851441 -0.51753318  0.         ... -1.29412271 -0.32259114
  -0.82122993]
 ...
 [ 0.20851441 -0.51753318  0.         ...  0.68836315 -1.04842119
  -0.82122993]
 [ 0.20851441 -0.51753318  0.         ...  0.68836315 -1.04842119
   1.21768576]
 [ 0.20851441 -0.51753318  0.         ...  0.68836315 -1.29036454
   1.21768576]]


In [13]:
print(Y)

[[-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [-1.3438112 ]
 [-1.3438112 ]
 [-1.3438112 ]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [-1.3438112 ]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [ 1.30699445]
 [ 1.30699445]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [ 1.30699445]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [-0.01840837]
 [-1.3438112 ]
 [-0.01840837]
 [-0.01840837]
 [ 1.30699445]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [ 1.30699445]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [-0.01840837]
 [-1.3438112 ]
 [-0.01840837]
 [-0.01840837]
 [-1.3438112 ]
 [-1.3438112 ]
 [ 1.30699445]
 [-1.3438112 ]
 [-0.01840837]
 [ 1.30699445]
 [ 2.63239728]
 [-0.01840837]
 [-0.01840837]
 [ 2.63239728]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [-0.01840837]
 [ 2.63239728]
 [-0.01840837]
 [-0.01840837]
 [ 2.63239

## Training the SVR model on the whole dataset

In [14]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, Y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

Predicting the test results

In [15]:
Y_pred = regressor.predict(X)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y.reshape(len(Y),1)),1))

[[-0.01 -0.02]
 [-0.12 -0.02]
 [-0.12 -0.02]
 [-0.12 -0.02]
 [-1.24 -1.34]
 [-1.24 -1.34]
 [-1.24 -1.34]
 [-1.24 -1.34]
 [-0.12 -0.02]
 [-0.12 -0.02]
 [-0.77 -1.34]
 [-0.72 -1.34]
 [-0.04 -0.02]
 [-0.1  -0.02]
 [-0.5  -1.34]
 [ 0.57  1.31]
 [ 0.57  1.31]
 [-0.12 -0.02]
 [ 0.08 -0.02]
 [ 0.08 -0.02]
 [ 1.1   1.31]
 [-0.09 -0.02]
 [-0.12 -0.02]
 [-0.74 -1.34]
 [-0.05 -0.02]
 [-0.31 -1.34]
 [-0.12 -0.02]
 [ 0.08 -0.02]
 [ 1.15  1.31]
 [-0.12 -0.02]
 [ 0.08 -0.02]
 [ 0.08 -0.02]
 [ 0.94  1.31]
 [-0.12 -0.02]
 [ 0.08 -0.02]
 [ 0.01 -0.02]
 [-0.08 -0.02]
 [ 0.08 -0.02]
 [-0.12 -0.02]
 [-0.5  -1.34]
 [ 0.08 -0.02]
 [-0.04 -0.02]
 [ 0.08 -0.02]
 [-0.02 -0.02]
 [-0.79 -1.34]
 [-0.12 -0.02]
 [-0.67 -1.34]
 [-0.12 -0.02]
 [ 0.08 -0.02]
 [-1.24 -1.34]
 [-1.07 -1.34]
 [ 0.1   1.31]
 [-1.03 -1.34]
 [ 0.08 -0.02]
 [ 1.18  1.31]
 [ 1.14  2.63]
 [ 0.08 -0.02]
 [ 0.08 -0.02]
 [ 0.61  2.63]
 [ 0.08 -0.02]
 [-0.01 -0.02]
 [ 0.05 -0.02]
 [-0.08 -0.02]
 [ 0.32  2.63]
 [ 0.08 -0.02]
 [ 0.08 -0.02]
 [ 0.64  2

In [16]:
print(regressor.coef_)
print(regressor.intercept_)

AttributeError: ignored

# Evaluating the Model Performance

In [17]:
from sklearn.metrics import r2_score
r2_score(Y, Y_pred)

0.6533173632754186